name: Deploy to Neocities

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.148.1'
          extended: true

      - name: Clean Public Folder
        run: rm -rf public

      - name: Build Hugo Site
        run: hugo

      - name: Remove large or problematic files
        run: |
          rm -f public/sitemap.xml
          rm -f public/index.xml
          rm -f public/posts/index.xml

        

      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_API_KEY }}
          dist_dir: public
